name: EZPRO Windows

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Windows info
        shell: powershell
        run: |
          Write-Host "Windows:"
          Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, OsBuildNumber

          Write-Host ""
          Write-Host "Public IP:"
          Invoke-RestMethod "https://api.ipify.org"

      - name: Create adminpanel
        shell: powershell
        run: |
          $password = "Adminhbr2026!"
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force

          $user = Get-LocalUser -Name "adminpanel" -ErrorAction SilentlyContinue

          if ($null -eq $user) {
              New-LocalUser `
                -Name "adminpanel" `
                -Password $securePassword `
                -FullName "EZPRO Admin" `
                -Description "EZPRO temporary user"
          }
          else {
              Set-LocalUser `
                -Name "adminpanel" `
                -Password $securePassword
          }

          Add-LocalGroupMember `
            -Group "Administrators" `
            -Member "adminpanel" `
            -ErrorAction SilentlyContinue

          Write-Host "User created."
          Write-Host "Username: adminpanel"
          Write-Host "Password: Adminhbr2026!"

      - name: Keep runner alive
        shell: powershell
        run: |
          Write-Host "EZPRO runner is running..."
          Start-Sleep -Seconds 300
